name: task_shop
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2

  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  sqflite: ^2.3.3
  path: ^1.9.0

  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.4

  supabase_flutter: ^2.6.0
